In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np.sum(x)

45

In [5]:
np.min(x)

1

In [6]:
np.max(x)

9

In [7]:
np.mean(x)

5.0

In [8]:
##application - mean

squares=[1,4,9,16]
sum_squares=sum(squares)
length=len(squares)
mean=sum_squares/length


squares1=np.array(squares)


In [9]:
squares1

array([ 1,  4,  9, 16])

In [10]:
np.mean(squares1)

7.5

In [11]:
np.std(squares1)

5.678908345800274

In [12]:
np.std(x)

2.581988897471611