In [1]:
import numpy as np

## Creating a matrix

In [2]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x[0,1] ##an element

2

In [5]:
x[1,2]

6

In [6]:
print(x[0]) ##access an entire row

[1 2 3]


In [7]:
x[0][1]

2

## Slicing

In [8]:
## x[i,j]

##x[i1:i2,j1:j2]

In [9]:
y=x[0:2,0:2]

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
y

array([[1, 2],
       [4, 5]])

In [12]:
y.shape

(2, 2)

In [13]:
x.shape

(3, 3)

In [14]:
z=np.array([[1,2,3],[4,5,6]])

In [15]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
z.shape

(2, 3)

In [17]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
##accessing columns

x[:,0]

array([1, 4, 7])

In [19]:
x[:,1]

array([2, 5, 8])

In [20]:
x[:,2]

array([3, 6, 9])